[environments]
  [environments.development]
    name = "onboarding-slackbot"
    namespace = "argus"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
